CREATE TABLE VCCB_ACQ_BANK_FEE 
(
       BANK_CODE VARCHAR2(20),
       NAPAS_FEE NUMBER(3,2),
       VISA_ACQ_FEE NUMBER(3,2),
       VISA_ISS_DOMESTIC_FEE NUMBER(3,2),
     VISA_ISS_FOREIGN_FEE NUMBER(3,2),
       MASTER_ACQ_FEE NUMBER(3,2),
     MASTER_ISS_DOMESTIC_FEE NUMBER(3,2),
     MASTER_ISS_FOREIGN_FEE NUMBER(3,2),
       JCB_ACQ_FEE NUMBER(3,2),
     JCB_ISS_DOMESTIC_FEE NUMBER(3,2),
     JCB_ISS_FOREIGN_FEE NUMBER(3,2),
     ACTIVE	NUMBER(1),
	   START_DATE DATE,
	   END_DATE DATE,
     IMPORT_ID NUMBER(22),
     FILE_ID NUMBER(22),
     IS_PROCESS_IMP NUMBER(1),
	   IMPORT_DATE DATE,
     rec_updated_date date  
);
CREATE INDEX VCCB_ACQ_BANK_FEE_IDX ON VCCB_ACQ_BANK_FEE (BANK_CODE)



select *
from VCCB_ACQ_BANK_FEE 
where active = 1 or end_date is null

select max(rec_updated_date), sysdate
from VCCB_ACQ_BANK_FEE




