CREATE TABLE VCCB_ACQ_VPB_ONL_TXN_TMP_IMP
(
  DEBIT_AMOUNT number(18,2),
  CREDIT_AMOUNT number(18,2),
  BALANCE_AMOUNT number(18,2),
  TERMINAL_ID VARCHAR2(20),
  TRANS_DATE DATE,
  CARD_NUMBER VARCHAR2(20),
  CARD_TYPE VARCHAR2(20),
  AUTH_CODE NUMBER(8),
  TRANS_AMOUNT NUMBER(18,2),
  FEE_AMOUNT NUMBER(18,2),
  VAT_AMOUNT NUMBER(18,2),
  RRN VARCHAR2(20),
  IMPORT_CONTENT VARCHAR2(250),
  FILE_ID NUMBER(22),
  DOC_ID varchar2(20),
  BATCH_NO NUMBER(3)
)


select * from VCCB_ACQ_VPB_ONL_TXN_TMP_IMP

SELECT *
FROM VCCB_ACQ_VPB_ONL_TXN_TMP_IMP
WHERE NVL(CREDIT_AMOUNT,0) > 0
AND NVL(DEBIT_AMOUNT, 0) = 0;

SELECT COUNT(*)

  FROM   (SELECT Rrn
          FROM   Vccb_Acq_Vpb_Onl_Txn_Tmp_Imp
          WHERE  Nvl(Credit_Amount, 0) > 0
                 AND Nvl(Debit_Amount, 0) = 0
          GROUP  BY Rrn
          HAVING COUNT(*) > 1);




