CREATE TABLE VCCB_ACQ_POS_BANK_CHARGE_FEE AS
(
       BANK_CODE VARCHAR2(10),
       NAPAS_BVB_FEE NUMBER(2,2),
       NAPAS_ACQ_FEE NUMBER(2,2),
       NAPAS_FEE NUMBER(2,2),
       VISA_BVB_FFE NUMBER(2,2),
       VISA_ACQ_FEE NUMBER(2,2),
       VISA_ISS_DOMESTIC_FEE NUMBER(2,2),
	   VISA_ISS_FOREIGN_FEE NUMBER(2,2),
	   MASTER_BVB_FEE NUMBER(2,2), 
       MASTER_ACQ_FEE NUMBER(2,2),
	   MASTER_ISS_DOMESTIC_FEE NUMBER(2,2),
	   MASTER_ISS_FOREIGN_FEE NUMBER(2,2),
	   JCB_BVB_FEE NUMBER(2,2), 
       JCB_ACQ_FEE NUMBER(2,2),
	   JCB_ISS_DOMESTIC_FEE NUMBER(2,2),
	   JCB_ISS_FOREIGN_FEE NUMBER(2,2),
	   ACTIVE	NUMBER(1),
	   START_DATE DATE,
	   END_DATE DATE,
	   IMPORT_DATE DATE  
)
