CREATE TABLE VCCB_ACQ_VPB_ONL_TXN
(
  IMPORT_ID NUMBER(22),
  FILE_ID NUMBER(22),
  DOC_ID varchar2(20),
  DEBIT_AMOUNT number(18,2),
  CREDIT_AMOUNT number(18,2),
  BALANCE_AMOUNT number(18,2),
  TERMINAL_ID VARCHAR2(20),
  TRANS_DATE DATE,
  CARD_NUMBER VARCHAR2(20),
  CARD_TYPE VARCHAR2(20),
  AUTH_CODE NUMBER(8),
  TRANS_AMOUNT NUMBER(18,2),
  FEE_AMOUNT NUMBER(18,2),
  VAT_AMOUNT NUMBER(18,2),
  FEE_PERCENT NUMBER(2,2),
  BANK_CODE VARCHAR2(10),
  MDR_FEE_CODE VARCHAR2(10),
  MDR_FEE_PERCENT NUMBER(2,2),
  MDR_FEE_AMOUNT NUMBER(18,2),
  RRN VARCHAR2(20),
  IMPORT_CONTENT VARCHAR2(250),
  BATCH_NO NUMBER(3),
  IMPORT_DATE DATE,
  IS_PROCESSED NUMBER(1),
  rec_updated_date date
  
)
PARTITION BY RANGE(IMPORT_DATE) INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))  
(PARTITION P1 VALUES LESS THAN (TO_DATE('01/09/2024', 'DD/MM/YYYY')));  
-- CREATE/RECREATE INDEXES 
CREATE INDEX VCCB_ACQ_VPB_ONL_TXN_IDX ON VCCB_ACQ_VPB_ONL_TXN (IMPORT_ID)


select * from VCCB_ACQ_VPB_ONL_TXN



