CREATE OR REPLACE VIEW VCCB_ACQ_BANK_TOTAL_TXN_RPT_VV AS
SELECT ROW_NUMBER() OVER ( ORDER BY TXN.IMP_SESSION,TXN.ACQ_BANK_CODE ) AS NO
       , TXN.IMP_SESSION AS RPT_SESSION
       , TXN.ACQ_BANK_CODE AS ACQ_BANK
       , COUNT(TXN.RETRIEVAL_REF_NO) AS NUM_OF_TXN
       , SUM(TXN.REQUEST_AMOUNT) AS TXN_AMT
       , SUM(TXN.ACQ_BANK_FEE) AS SHARE_FEE
       , SUM(TXN.BVB_CREDIT_AMT) AS BVB_AMT
FROM   VCCB_ATOM_POS_SETTL_TXN_IMP TXN
LEFT JOIN
(
     SELECT MAX(IMP_SESSION) IMP_SESSION
     FROM VCCB_ATOM_POS_SETTL_TXN_IMP
     WHERE  IMPORT_DATE = TRUNC(SYSDATE)
      AND IS_SETTLE = 1
      AND RESPONSE_CODE = '00'
)m ON m.IMP_SESSION = TXN.IMP_SESSION
WHERE  TXN.IMPORT_DATE = TRUNC(SYSDATE)
      AND TXN.IS_SETTLE = 1
      AND TXN.RESPONSE_CODE = '00'
      AND m.IMP_SESSION is not null
GROUP BY TXN.IMP_SESSION,TXN.ACQ_BANK_CODE
ORDER BY TXN.IMP_SESSION,TXN.ACQ_BANK_CODE;
