-- Create table
create table VCCB_ATOM_POS_SETTL_TXN_TMP
(
  record_date              DATE,
  merchant_name            VARCHAR2(250),
  master_merchant          VARCHAR2(250),
  merchant_id              VARCHAR2(20),
  terminal_id              VARCHAR2(20),
  serial_no                VARCHAR2(100),
  batch_no                 VARCHAR2(15),
  invoice_no               VARCHAR2(15),
  card_number              VARCHAR2(20),
  card_type                VARCHAR2(15),
  card_origin              NUMBER(1),
  request_amount           NUMBER(18,2),
  is_settle                NUMBER(1),
  is_void                  NUMBER(1),
  is_reversal              NUMBER(1),
  auth_id_reponse          VARCHAR2(100),
  issuer_bank              VARCHAR2(15),
  orig_txn_date            DATE,
  response_code            VARCHAR2(3),
  retrieval_ref_no         VARCHAR2(15),
  settle_unix_time         DATE,
  txn_id                   VARCHAR2(50),
  void_txn_id              VARCHAR2(50),
  void_unix_time           VARCHAR2(15),
  reversal_txn_id          VARCHAR2(50),
  reversal_time            VARCHAR2(15),
  merchant_fee_rate        NUMBER(4,2),
  master_merchant_fee_rate NUMBER(4,2),
  cost_price_rate          NUMBER(4,2),
  mcc                      VARCHAR2(250),
  acq_bank_code            VARCHAR2(15),
  transaction_type         VARCHAR2(15),
  pos_entry_mode           VARCHAR2(6),
  master_merchant_fee      NUMBER(18,2),
  acq_bank_fee             NUMBER(18,2),
  bvb_credit_amt           NUMBER(18,2),
  discount_amt             NUMBER(18,2),
  merchant_credit_amt      NUMBER(18,2),
  account_number           VARCHAR2(20),
  account_name             VARCHAR2(250),
  file_id                  NUMBER(10),
  imp_rec_id               NUMBER(8)
)
;
