CREATE OR REPLACE VIEW VCCB_ACQ_MER_TOTAL_TXN_RPT_VV AS
SELECT ROW_NUMBER() OVER ( ORDER BY TXN.MERCHANT_NAME ) AS NO
       ,TXN.IMP_SESSION as RPT_SESSION
       , TXN.MERCHANT_NAME AS MERCHANT_NAME
       , TXN.MERCHANT_ID MID
       , TXN.TERMINAL_ID TID
       , COUNT(TXN.RETRIEVAL_REF_NO) AS NUM_OF_TXN
       , SUM(TXN.REQUEST_AMOUNT) AS TXN_AMT
       , SUM(TXN.DISCOUNT_AMT) AS DISCOUNT_AMT
       , SUM(TXN.MERCHANT_CREDIT_AMT) AS MERCHANT_CREDIT_AMT
       , TXN.ACCOUNT_NUMBER
       , TXN.ACCOUNT_NAME
FROM   VCCB_ATOM_POS_SETTL_TXN_IMP TXN
LEFT JOIN
(
     SELECT MAX(IMP_SESSION) IMP_SESSION
     FROM VCCB_ATOM_POS_SETTL_TXN_IMP
     WHERE  IMPORT_DATE = TRUNC(SYSDATE)
      AND IS_SETTLE = 1
      AND RESPONSE_CODE = '00'
)m ON m.IMP_SESSION = TXN.IMP_SESSION
WHERE  TXN.IMPORT_DATE = TRUNC(SYSDATE)
      AND TXN.IS_SETTLE = 1
      AND TXN.RESPONSE_CODE = '00'
      AND m.IMP_SESSION is not null
GROUP BY TXN.IMP_SESSION,TXN.MERCHANT_NAME, TXN.MERCHANT_ID, TXN.TERMINAL_ID, TXN.ACCOUNT_NUMBER, TXN.ACCOUNT_NAME
ORDER BY TXN.IMP_SESSION,TXN.MERCHANT_NAME;
