-- Create table
create table VCCB_RECONCILIATION_STB_IMP
(
  merchant_id          VARCHAR2(15),
  mm_dba_name          VARCHAR2(250),
  terminal_id          VARCHAR2(15),
  batch_no             NUMBER(8),
  invoice_no           VARCHAR2(15),
  settle_date          VARCHAR2(15),
  settle_time          VARCHAR2(15),
  trans_date           VARCHAR2(15),
  trans_time           VARCHAR2(15),
  card_no              VARCHAR2(19),
  trans_amount         NUMBER(18,2),
  curr_rate            NUMBER(4,2),
  billing_amount       NUMBER(18,2),
  discount             NUMBER(18,2),
  net_amount           NUMBER(18,2),
  approve_code         VARCHAR2(15),
  approve_code_sale    VARCHAR2(15),
  proc_date            VARCHAR2(15),
  book_date            VARCHAR2(15),
  discount_rate        NUMBER(4,2),
  crd_type             VARCHAR2(15),
  status               VARCHAR2(15),
  mm_biz_name          VARCHAR2(250),
  acq_ref_no           VARCHAR2(50),
  req_rec_id           VARCHAR2(50),
  customer_description VARCHAR2(15),
  reference_no         VARCHAR2(50),
  bill_code            VARCHAR2(15),
  customer_name        VARCHAR2(250),
  service_cd           VARCHAR2(15),
  real_card            VARCHAR2(19),
  qr_ssp               VARCHAR2(15),
  transaction_id       VARCHAR2(50),
  pos_entry            VARCHAR2(15),
  curr_type            VARCHAR2(3),
  order_id             VARCHAR2(15),
  file_id              NUMBER(10),
  imp_rec_id           NUMBER(22),
  import_date          DATE,
  imp_session          NUMBER(3),
  rec_created_date     DATE,
  rec_updated_date     DATE,
  is_processed         NUMBER(1),
  is_matched           NUMBER(1)
)
PARTITION BY RANGE(IMPORT_DATE) INTERVAL (NUMTOYMINTERVAL(1,'MONTH'))  
(PARTITION P1 VALUES LESS THAN (TO_DATE('01/01/2025', 'DD/MM/YYYY')));  
CREATE INDEX vccb_recon_stb_imp_mid_idx ON vccb_reconciliation_stb_imp (MERCHANT_ID);
CREATE INDEX vccb_recon_stb_imp_tid_idx ON vccb_reconciliation_stb_imp (TERMINAL_ID);